---
title: "Homework 5"
author: "Wyatt Deaderick"
date: "2022-11-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(lubridate)
```

```{r read_data}
homicide_data <- read_csv("data/homicide-data.csv")
```

```{r data_cleaning}
homicide_data <- homicide_data %>% 
  filter(city == "Baltimore") %>% 
  mutate(reported_date = ymd(reported_date),
         reported_month = month(reported_date), 
         reported_year = year(reported_date),
         reported_my = my(paste(reported_month, reported_year, sep = "-")))
         
homicide_data <- homicide_data %>%        
  mutate(season = if_else(homicide_data$reported_month %in% c(11, 12, 1, 2, 3, 4), 
                          "Winter", "Summer")) %>% 
  group_by(reported_year, reported_month) %>% 
  mutate(n = n()) %>% 
  ungroup()
```

```{r plotting}
homicide_data %>% 
  ggplot(mapping = aes(x = reported_my)) +
  geom_bar(aes(fill = season))+
  geom_smooth(aes(y = n), se = FALSE)+
  geom_vline(xintercept = ymd(20150412), linetype = 2, color = "red", size = 1)+
  annotate("text",
           x = ymd(20140501), 
           y = 40, 
           label = "Arrest of \n Freddie Gray" , 
           color = "light grey")+
  ylab("Monthly Homicides")+
  xlab("Date")+
  ggtitle("Homicides in Baltimore, MD")+
  theme_dark()+
  theme(legend.position = "bottom")+
  scale_fill_manual(values = c("grey", "light blue"), name = NULL)
```